server:
  address: 0.0.0.0
  # port: 8100
spring:
   http:
      encoding:
         charset: UTF-8
         enabled: true
         force: true
   thymeleaf:
      cache: false
   cs:
      upload:
         dir: F://upload/
   datasource:
      url: jdbc:sqlite:F://timetable.db
      # url: jdbc:sqlite:/usr/cs/data/timetable.db
      driverClassName: org.sqlite.JDBC
      username: 
      password:
   jpa:
      database-platform: org.hibernate.dialect.SQLiteDialect
      generate-ddl: true
      hibernate:
         ddl-auto: update
      # show-sql: true
      open-in-view: false


logging:
   level:
      com:
         jytec:
            cs:
               excel: DEBUG

    